ControlMachine=Node1
MpiDefault=pmi2
ProctrackType=proctrack/linuxproc
ReturnToService=2
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=root
SlurmdUser=root
StateSaveLocation=/var/spool/slurm
SwitchType=switch/none
TaskPlugin=task/none

ClusterName=cluster
JobAcctGatherType=jobacct_gather/linux
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmdDebug=debug2

SlurmctldDebug=5
SlurmctldLogFile=/var/log/slurm/slurmctld.log
DebugFlags=gres

NodeName=Node2 NodeAddr=192.168.1.2 CPUs=64 RealMemory=64000 Sockets=64 CoresPerSocket=1 ThreadsPerCore=1 STATE=UNKNOWN
NodeName=Node3 NodeAddr=192.168.1.3 CPUs=64 RealMemory=64000 Sockets=64 CoresPerSocket=1 ThreadsPerCore=1  STATE=UNKNOWN
NodeName=Node4 NodeAddr=192.168.1.4 CPUs=64 RealMemory=64000 Sockets=64 CoresPerSocket=1 ThreadsPerCore=1  STATE=UNKNOWN

PartitionName=cpu-node Nodes=Node2,Node3,Node4 Default=NO MaxTime=INFINITE  State=UP
JobAcctGatherFrequency=8
